#!/bin/env node

const child_process = require("node:child_process");
const { exit } = require("node:process");

if (!process.argv[2]) {
	console.log("No input provided");
	exit(1);
} else if (process.argv[3]) {
	console.log("Command takes only 1 input");
	exit(1);
}

const input = JSON.parse(process.argv[2]);
const args = Object.keys(input).flatMap(option => {
	if (option === "production") {
		return input[option] === true ? ["--prod"] : [];
	} else {
		return [`--${option}`, input[option]];
	}
});

child_process.execFile(
	"./node_modules/.bin/netlify",
	["deploy", "--json", ...args],
	(error, stdout, stderr) => {
		if (error || stderr) {
			console.log(error, stderr);
		} else {
			const data = JSON.parse(stdout);
			console.log(JSON.stringify(data));
		}
	}
);
